repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1200"]
        files: ^zkml/
      - id: check-case-conflict
        files: ^zkml/
      - id: check-merge-conflict
        files: ^zkml/
      - id: check-symlinks
        files: ^zkml/
      - id: check-yaml
        files: ^zkml/
      - id: debug-statements
        files: ^zkml/
      - id: end-of-file-fixer
        exclude: "^docs/examples/"
        files: ^zkml/
      - id: fix-encoding-pragma
        files: ^zkml/
      - id: requirements-txt-fixer
        files: ^zkml/
      - id: trailing-whitespace
        files: ^zkml/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        files: ^zkml/

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        # args: [--line-length 79]
        files: ^zkml/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: docs/conf.py
        additional_dependencies: [flake8-bugbear, flake8-print]
        files: ^zkml/

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [manual]
        files: ^zkml/

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
        args: [--nbqa-dont-skip-bad-cells]
        additional_dependencies: [black==22.3.0]
        files: ^zkml/
      - id: nbqa-isort
        args: [--nbqa-dont-skip-bad-cells]
        additional_dependencies: [isort==5.6.4]
        files: ^zkml/
      - id: nbqa-flake8
        args: [--nbqa-dont-skip-bad-cells, "--extend-ignore=E402,E203"]
        additional_dependencies: [flake8==3.8.3]
        files: ^zkml/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--config=setup.cfg"]
        exclude: "tests/__init__.py"
        files: ^zkml/
